name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    # - name: Xcode Porject
    #   run: swift package generate-xcodeproj
    - name: Build
      run: swift build --generate-xcodeproj -v
    - name: Run tests
      run: swift test --generate-xcodeproj -v
